# Generated by Django 4.2.15 on 2024-10-18 18:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(allow_unicode=True, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(allow_unicode=True, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(allow_unicode=True, unique=True)),
                (
                    "image",
                    models.ImageField(
                        default="/default/product-image.png", upload_to="product/img/"
                    ),
                ),
                ("description", models.TextField()),
                ("brief_description", models.TextField(blank=True, null=True)),
                ("docNo", models.CharField(blank=True, max_length=255, null=True)),
                ("vendor", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "manufacturerPartNo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "supplierPartNo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "discipline",
                    models.IntegerField(
                        choices=[
                            (1, "مکانیک"),
                            (2, "ماشین آلات دوار"),
                            (3, "ابزار دقیق"),
                            (4, "برق"),
                            (5, "متفرقه"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "equipmentType",
                    models.IntegerField(
                        choices=[
                            (1, "پمپ"),
                            (2, "کمپرسور"),
                            (3, "مبدل"),
                            (4, "برج"),
                            (5, "تانک"),
                            (6, "طبل"),
                            (7, "خاص"),
                            (8, "تجهیزات"),
                            (9, "دیگر"),
                        ],
                        default=9,
                    ),
                ),
                (
                    "equipmentTagNo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "processUnit",
                    models.IntegerField(
                        choices=[(1, "آمونیاک"), (2, "اوره"), (3, "آب صنعتی")],
                        default=1,
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                ("isManufactured", models.BooleanField(default=False)),
                (
                    "manufactured",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "originalUnitPrice",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                (
                    "currency",
                    models.IntegerField(
                        choices=[(1, "دلار"), (2, "یورو"), (3, "درهم"), (4, "یوان")],
                        default=1,
                    ),
                ),
                (
                    "exchangeRate",
                    models.IntegerField(
                        choices=[(1, "دلار"), (2, "یورو"), (3, "درهم"), (4, "یوان")],
                        default=1,
                    ),
                ),
                ("ManufacturedData", models.DateTimeField(blank=True, null=True)),
                ("savingMony", models.FloatField(blank=True, null=True)),
                (
                    "Satisfaction",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "نمایش"), (2, "عدم نمایش")], default=2
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                (
                    "discount_percent",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("avg_rate", models.FloatField(default=0.0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "ManufacturedForPlant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_ManufacturedForPlant",
                        to="shop.planttype",
                    ),
                ),
                ("category", models.ManyToManyField(to="shop.productcategorymodel")),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_plant",
                        to="shop.planttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="WishlistProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.productmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="product/extra-img/")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_images",
                        to="shop.productmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="ProductFileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="product/files/")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_files",
                        to="shop.productmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_date"],
            },
        ),
    ]
