# Generated by Django 4.2.16 on 2024-10-03 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='ManufacturedData',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='ManufacturedForPlant',
            field=models.IntegerField(choices=[(1, 'کرمان'), (2, 'شیراز'), (3, 'پردیس')], default=1),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='Satisfaction',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='currency',
            field=models.IntegerField(choices=[(1, 'دلار'), (2, 'یورو'), (3, 'درهم'), (4, 'یوان')], default=1),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='discipline',
            field=models.IntegerField(choices=[(1, 'مکانیک'), (2, 'ماشین آلات دوار'), (3, 'ابزار دقیق'), (4, 'برق'), (5, 'متفرقه')], default=5),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='docNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='equipmentTagNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='equipmentType',
            field=models.IntegerField(choices=[(1, 'پمپ'), (2, 'کمپرسور'), (3, 'مبدل'), (4, 'برج'), (5, 'تانک'), (6, 'طبل'), (7, 'خاص'), (8, 'تجهیزات'), (9, 'دیگر')], default=9),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='exchangeRate',
            field=models.IntegerField(choices=[(1, 'دلار'), (2, 'یورو'), (3, 'درهم'), (4, 'یوان')], default=1),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='isManufactured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='manufactured',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='manufacturerPartNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='originalUnitPrice',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='plant',
            field=models.IntegerField(choices=[(1, 'کرمان'), (2, 'شیراز'), (3, 'پردیس')], default=1),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='processUnit',
            field=models.IntegerField(choices=[(1, 'آمونیاک'), (2, 'اوره'), (3, 'آب صنعتی')], default=1),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='savingMony',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='supplierPartNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
