# Generated by Django 4.2.15 on 2024-10-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productfilemodel",
            name="title",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
