# Generated by Django 4.2.15 on 2024-10-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="exchangeRate",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
